seuros/capistrano-sidekiq

lib/capistrano/tasks/monit.cap
PR to try `execute` on the monit.conf `mv` command in case the deploy user doesn't have sudo for `mv`. In our deploy environment, we don't want the deploy user to have general sudo access, only to the commands that are essential (e.g. `monit`). So this plugin works fine except the deploy user needs sudo to `mv` to move the file out of `/tmp` into the monit config dir.
=> Try execute on the monit.conf mv command

README.md, lib/capistrano/tasks/capistrano2.rb, lib/capistrano/tasks/sidekiq.cap
Hi there,
We are interested in booting different processes for different queues, because some jobs are really slow and might saturate our workers. I've been thinking about it and I think this is a very simple way to just let people customize every process. This could be improved in many ways, like different options per server/role and all that, but I think it's simple enough as it is, and would be pretty useful to many people.
I hope you consider merging this. In any case, thanks a lot for this project, it's worked really great for us!
Cheers!
=> Options per process

lib/capistrano/tasks/capistrano2.rb
Copied from [the cap3 version](https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/sidekiq.cap#L97).
=> Support sidekiq_concurrency option for capistrano 2

lib/capistrano/tasks/capistrano2.rb
A ``fetch(:sidekiq_concurrency)``` call throws an exception if no sidekiq_concurrency has been set. This pull-request simply adds a default nil value.
=> Set sidekiq_concurrency default value for cap 2 (improves pr #72).

README.md, lib/capistrano/sidekiq/version.rb, lib/capistrano/tasks/capistrano2.rb, lib/capistrano/tasks/sidekiq.cap
Now we can customize how many processes capistrano has to run on each server.
set :sidekiq_role, [:sidekiq, :sidekiq_small, :sidekiq_big]
set :sidekiq_small_processes, 2
set :sidekiq_big_processes, 4
role :sidekiq, 'sidekiq.example.com'
role :sidekiq_small, 'sidekiq_small.example.com'
role :sidekiq_big, 'sidekiq_big.example.com'
It was very helpfull for me because we use different AWS-S3 instancess for sidekiq. I hope it will be helpfull for other developers.
=> implemented ability to split sidekiq_roles by count of sidekiq-processes

lib/capistrano/tasks/sidekiq.cap
This Pull Request will fix pty problem.
I tried to apply this branch, and starting sidekiq was success with
```ruby
set :pty, true
```
Please consider this.
=> Add nohup when executing start_sidekiq command, for a problem with pty.

README.md, lib/capistrano/tasks/monit.cap, lib/capistrano/tasks/sidekiq.cap
- removed unused filenames
- use ```File.join``` for referring to original template
- removed some redundancy
- split ```template_sidekiq``` into two separate methods for generating filename and uploading file
=> Refactored template_sidekiq method

README.md, lib/capistrano/sidekiq/version.rb, lib/capistrano/tasks/monit.cap
Support for different number of processes per host has already been merged on master, but was missing from monit.cap.
This PR should fix that issue.
=> Add support for different number of processes per host on monit.cap

lib/capistrano/tasks/capistrano2.rb, lib/capistrano/tasks/sidekiq.cap
As mentioned in https://github.com/seuros/capistrano-puma/issues/115 this is an attempt to implement a similiar concept in the sidekiq recipe as well. Please let me know if there's anything you'd like to have added or if I maybe forgot something.
=> intial support for sidekiq_user

README.md, lib/capistrano/tasks/sidekiq.rake, lib/generators/capistrano/sidekiq/monit/templates/sidekiq_monit.conf.erb
Same as https://github.com/seuros/capistrano-puma/pull/128
We don't need to explicitly specify the `bundle exec` statement(actually, we shouldn't).
The best practice is [add the binaries to the bundle_bins array](https://github.com/capistrano/bundler/blob/master/lib%2Fcapistrano%2Ftasks%2Fbundler.cap#L44-L47).
With following the best practice, the user can easily to custom the execution command, for example, I am  going to use the [dotenv](https://github.com/bkeepers/dotenv) executable to launch the sidekiq. I can add an additive task like this:
```
namespace :bundler do
task :map_bins do
fetch(:bundle_bins).each do |command|
SSHKit.config.command_map.prefix[command.to_sym].push('dotenv')
end
end
end
```
=> Use SSHKit command_map

README.md, lib/capistrano/tasks/capistrano2.rb, lib/capistrano/tasks/sidekiq.rake
Hello!
I've got a few minor fixes for capistrano 2 that we encountered when trying to use this in our setup:
* There was an extraneous `pty: false` at the end of a `run_as` command
* `sidekiq_user` was not optional like it was in the capistrano 3 task
* The capistrano 3 task was using `puma_user` and not `sidekiq_user`
* Made `sidekiq_user` `nil` by default and added some documentation
Thanks!
=> Capistrano 2 fixes

lib/capistrano/tasks/capistrano2.rb, lib/capistrano/tasks/sidekiq.rake
Fix this issue. https://github.com/seuros/capistrano-sidekiq/issues/44
Changed always add index to pidfile.
=> Change pidfile handling, always add index to pidfile name

lib/capistrano/tasks/monit.rake, lib/capistrano/tasks/sidekiq.rake, lib/generators/capistrano/sidekiq/monit/templates/sidekiq_monit.conf.erb
The main point of this PR is for the monit config to respect the `sidekiq_user` setting (per https://github.com/seuros/capistrano-sidekiq/issues/121#issuecomment-155222696).
It also normalizes behavior between capistrano-puma's and capistrano-sidekiq's respective `:puma_user` and `:sidekiq_user` options. (That is, if https://github.com/seuros/capistrano-puma/pull/139 is accepted.) I imagine many people use both of these gems, and IMHO this subtle difference in their behavior is non-obvious and confusing.
=> Respect both local and global puma_user setting everywhere

README.md
This configuration option can be set with successful results but was
undocumented.
@seuros I'm currently using this setting but I'm hoping that, by documenting it, it will stick around in future versions!
=> Documenting sidekiq_service_name config option

capistrano-sidekiq.gemspec, lib/capistrano/tasks/sidekiq.rake
After the long discussion of the issue (capistrano/capistrano#1686) related to re-enabling capistrano tasks, there was merged PR that introduced new `#invoke!`, that should resolve custom rake task re-enabling [here](https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/sidekiq.rake#L157) and [capistrano-sneakers](https://github.com/inventionlabsSydney/capistrano-sneakers/blob/master/lib/capistrano/tasks/sneakers.rb#L192).
- inventionlabsSydney/capistrano-sneakers/pull/7
=> Use new capistrano DSL for reenable tasks

README.md, lib/capistrano/sidekiq/monit.rb, lib/capistrano/tasks/monit.rake, lib/capistrano/tasks/sidekiq.rake
🎄 Hi, thanks for the wonderful tool ❤️  
I reviewed the codebase to understand better, how `capistrano-sidekiq` works internally. And I found a couple of places that could be more clearly described.
Also I took the liberty to correct [Wiki page](https://github.com/seuros/capistrano-sidekiq/wiki/Home/_compare/d2d1bc70b1721be1681721bf1ab0b263b0814d4f...f43189ea34f06924194d9682a27b58f98c3bd4ea), because `capistrano-rails` gem doesn't imply on sidekiq deployment flow (default hooks enable inside `capistrano-sidekiq` gem itself) and `pty: false` is a Capistrano 3 default for a pretty long time.
=> Christmas Eve Cleaning 🎅 

README.md, lib/capistrano/tasks/monit.rake, lib/capistrano/tasks/sidekiq.rake
At the moment is not separated from the rest of the service name – `sidekiq_app_staging0`. I'd like to have the process index at the end of the service name separated by an underscore – `sidekiq_app_staging_0`.
This change will require re-configure existing sidekiq-monit setups, so probably minor version upgrade is required.
- Set and describe `sidekiq_monit_group` explicitly
- Replace block calls for the scalar values
=> Prepend _ Before Service Name Index

README.md
This PR puts a simple note on how to have capistrano-sidekiq prepend `bundle exec` to `sidekiq` and `sidekiqctl` commands post [this commit](https://github.com/seuros/capistrano-sidekiq/commit/8a49d7608e08a61a6f9d652225014565caecd982#diff-53bde90b6868f694716f646b4065f8beR118).
=> update README with instructions for prepending 'bundle exec'

capistrano-sidekiq.gemspec, lib/capistrano/tasks/monit.rake
I'm using monit-5.9 and our server config requires a custom path and extension e.g
`/usr/local/etc/monit.d/foobar-worker.monitrc` instead of *.conf file. I managed to override the custom folder path but not the file name. Hence this PR exists.
Please help reviewing. It has been manually tested.
```
set :sidekiq_monit_conf_dir, '/usr/local/etc/monit.d'
set :sidekiq_monit_conf_file, 'service-worker.monitrc'
set :monit_bin, '/usr/local/bin/monit'
```
=> Support custom monit filename

CHANGELOG.md, lib/capistrano/tasks/sidekiq.rake
Fixes #191 
This regression was introduced by #190, due to a minor refactor on the method to retrieve the pidfiles for a particular host's roles. 
In sum, the `sidekiq_roles` variable was being mutated by a `.reject!` statement and would only work properly for the first method call (for more context check the corresponding issue).
I took the liberty to do a few styling corrections, suggested by Rubocop. Also included the breaking change from `sidekiq_role` to `sidekiq_roles` that happened on `1.0.0` to the corresponding changelog entry.
=> Fix accounting of pidfiles per process (when using multiple processes)

lib/capistrano/tasks/sidekiq.rake
After upgrading from 0.20.0 to 1.0.0, The following errors occured
```
ArgumentError: wrong number of arguments (given 1, expected 0)
capistrano-sidekiq-1.0.0/lib/capistrano/tasks/sidekiq.rake:134:in `each_process_with_index'
capistrano-sidekiq-1.0.0/lib/capistrano/tasks/sidekiq.rake:94:in `block (4 levels) in <top (required)>'
capistrano-sidekiq-1.0.0/lib/capistrano/tasks/sidekiq.rake:206:in `switch_user'
capistrano-sidekiq-1.0.0/lib/capistrano/tasks/sidekiq.rake:91:in `block (3 levels) in <top (required)>'
```
The cause is that the argument has changed
https://github.com/seuros/capistrano-sidekiq/blob/v0.20.0/lib/capistrano/tasks/sidekiq.rake#L32
https://github.com/seuros/capistrano-sidekiq/blob/v1.0.0/lib/capistrano/tasks/sidekiq.rake#L132
=> fix fail rolling restart task

lib/capistrano/tasks/monit.rake, lib/generators/capistrano/sidekiq/monit/templates/sidekiq_monit.conf.erb
1.sidekiq_service_name cann't fetch application at initialization phase.Using block works.
2.replace `fetch(:sidekiq_monit_group, fetch(:application)` with `fetch(:sidekiq_monit_group) || fetch(:application)`
see issue  https://github.com/seuros/capistrano-sidekiq/issues/204
=> Fix monit config file name missing application

README.md
Without adjusting the process number the configured second queue will never be started.
Indicating this in the REAMDE might keep others from making the same mistake.
=> Update README#Multiple processes example

lib/generators/capistrano/sidekiq/systemd/templates/sidekiq.service.capistrano.erb
Since sidekiq 6 no longer supports logfile (-l) option - switch to StandardOutput systemd option.
https://github.com/mperham/sidekiq/blob/master/Changes.md#60
https://github.com/mperham/sidekiq/issues/4335#issuecomment-541346972
=> Use StandardOutput for logging

README.md, lib/capistrano/sidekiq/systemd.rb, lib/capistrano/tasks/systemd.rake
Without lingering sidekiq systemd process will be shutdown.
> The systemd user instance is started after the first login of a user and killed after the last session of the user is closed. Sometimes it may be useful to start it right after boot, and keep the systemd user instance running after the last session closes, for instance to have some user process running without any open session. Lingering is used to that effect. 
From https://wiki.archlinux.org/index.php/Systemd/User
By default `loginctl enable-linger` enables lingering for current user. We can add variable if needed.
=> Add "loginctl enable-linger" command to sidekiq systemd install task

lib/generators/capistrano/sidekiq/systemd/templates/sidekiq.service.capistrano.erb
Capistrano rbenv and other similar tools use **bundle exec** instead of **bundler exec**. So they  map SSHKit.config.command_map[:bundle] instead of SSHKit.config.command_map[:bundler].
=> Capistrano rbenv uses bundle instead of bundler

lib/capistrano/tasks/upstart.rake
This updates ignores `reload` and `stop` errors when upstart service is not running, which prevents Capistrano from completing deployment.
=> Upstart update

lib/capistrano/tasks/monit.rake, lib/capistrano/tasks/sidekiq.rake, lib/generators/capistrano/sidekiq/monit/templates/sidekiq_monit.conf.erb
This update makes monit integration functional again. It has been broken since Sidekiq 6.0 was released with removed daemonization, pidfile and logfile options (mperham/sidekiq#4045)
=> Update monit integration against Sidekiq 6.0

lib/capistrano/sidekiq.rb, lib/capistrano/sidekiq/helpers.rb, lib/capistrano/sidekiq/monit.rb, lib/capistrano/sidekiq/systemd.rb, lib/capistrano/sidekiq/upstart.rb, lib/capistrano/tasks/monit.rake, lib/capistrano/tasks/systemd.rake, lib/capistrano/tasks/upstart.rake
This PR fixes a bug in the `switch_user` function which would needlessly invoke `sudo` when the role user is the same as the `sidekiq` user. 
Furthermore, this PR also reduces code duplication (which was likely the source of the above bug).
Fixes #267.
=> Fix bug in switch_user and dry up common methods to a helpers module

lib/capistrano/tasks/systemd.rake
This line https://github.com/seuros/capistrano-sidekiq/blob/a4346067cd0af1124129cf27169edc98d4c015a0/lib/capistrano/tasks/systemd.rake#L82 has a trailing `/`, causing the `mv` destination path to be `/etc/systemd/system//sidekiq.service`.
=> Use File.join for systemd file path

README.md, lib/capistrano/sidekiq/helpers.rb, lib/capistrano/sidekiq/systemd.rb, lib/capistrano/tasks/sidekiq.rake, lib/capistrano/tasks/systemd.rake, lib/generators/capistrano/sidekiq/systemd/templates/sidekiq.service.capistrano.erb
I've tried to cleanup the overall systemd support in this repository. I've merged in a few other contributors PRs (#262 and #265) since they both were of use to me at some point.
Here are the major changes
- Tried to refactor and cleanup the tasks for managing systemd as a whole.
- Support for multiple Sidekiq processes via `set :sidekiq_processes, 3` which was previously removed I guess. This uses systemd's built in functionality to support multiple processes. The service file gets named `sidekiq@.service` and then processes are managed using `systemctl [command] sidekiq@{1..2}`.
- Updated the systemd template using the [official example](https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service).
- Proper Restart Task
- Runs Quiet (`systemctl kill -s TSTP …
=> Various systemd improvements - Multiple Process Support, Per Process Config, Proper Restarts with timeout and more

lib/capistrano/tasks/systemd.rake, lib/generators/capistrano/sidekiq/systemd/templates/sidekiq.service.capistrano.erb
`systemd` integration was add in #171, but it doesn't take into account `sidekiq_config`, `sidekiq_concurrency`, and `sidekiq_queue`, this PR fixes this so the generated `sidekiq.service` includes them in `ExecStart`, if they exist.
=> Add sidekiq_config, sidekiq_concurrency, and sidekiq_queue support to systemd

README.md, lib/capistrano/sidekiq/systemd.rb, lib/capistrano/tasks/systemd.rake
I added the possibility to use a custom .erb template for systemd.
In my case it was useful to manage old versions of systemd in which "append:" was not supported for StandardOutput and StandardError.
=> Added sidekiq_service_templates_path to manage custom systemd templates

lib/capistrano/tasks/systemd.rake
Solves the `undefined method 'present?' for nil:NilClass`, since we dont depend or define on anything that defines a `.present?` method, such as activesupport.
=> Avoid using present?

README.md
Explain what happens to Sidekiq log messages when installing on systems with a System version older than v240.
Closes #283.
=> README: Add section about older Systemd versions logging

lib/generators/capistrano/sidekiq/systemd/templates/sidekiq.service.capistrano.erb
Based on this comment https://github.com/systemd/systemd/issues/2690#issuecomment-186973730 `WantedBy` should be `default.target` for `--user` mode to let service start on system boot.
=> Fixed sidekiq.service autostart in --user mode

lib/generators/capistrano/sidekiq/systemd/templates/sidekiq.service.capistrano.erb
This PR restoring sidekiq_unit_env_vars option.
If memory usage wants reduce,  that better define on unit_env_vars.
Please review it.
Regards.
=> restore sidekiq unit env vars

lib/capistrano/tasks/systemd.rake
```diff
- ['systemd-clgs', '--user']
+ ['systemd-cgls', '--user']
```
=> Fix a typo in sidekiq:restart

lib/capistrano/tasks/systemd.rake
This updates the uploading of systemd service files for multiple process sidekiq workers. It does not break existing codebases by implementing a naming structure like `sidekiq@1.service` where only a single process is requested.
Connects to https://github.com/seuros/capistrano-sidekiq/issues/298
=> Support multiple processes in `sidekiq:install`

lib/generators/capistrano/sidekiq/monit/templates/sidekiq_monit.conf.erb
The config template had a couple issues that made it not work.
- The `check process` line was indented when it should not have been.
- The use of `fetch(:full_app_name)` instead of `fetch(:application)`. No idea where `:full_app_name` was supposed to come from, but, at least for me, it doesn't exist.
- The use of `ps -ax` instead of `ps ax`. The former would produce a warning because `ps -aux` is distinct from `ps aux`.
Also, formatted the comment to match the puma plugin's template for consistency.
=> fix: monit config template

lib/capistrano/tasks/sidekiq.rake
The gem adds hooks for stopping sidekiq after the `deploy:updated` step. This is sufficient for a regular capistrano deploy. However, during a capistrano `deploy:rollback`, the flow is different and `deploy:updated` is not called. Instead, `deploy:reverted` is called. [Here's a link to the Capistrano documentation explaining the flows.](https://capistranorb.com/documentation/getting-started/flow/)
In order to make rollbacks work properly, we need to also add a hook to run `sidekiq:stop` on `deploy:reverted`. This PR adds that hook.
=> Inject sidekiq:stop after deploy:reverted

lib/capistrano/sidekiq.rb
Fixes #327
The 'as' method needs to be called on the backend object, not directly. This change properly invokes the SSHKit backend method for switching user context during remote command execution.
=> Fix undefined method 'as' error by using backend.as
